### PR TITLE
Create task

### PR DESCRIPTION
**Pull request by somaiyappan**
Task

### CODE REVIEW

**Comment by ashish-mw** [comment]
Thanks for the PR @somaiyappan 

Could you please add more details as mentioned in the `questions.md` file? 
There is a section titled Introductions, could you please add answers to those?

**Comment by somaiyappan** [comment]
Yes, I done it sir

**Comment by ashish-mw** [comment]
Sorry! I cant see it in the PR @somaiyappan 
Please go through https://github.com/mindwaveventures/join-us/blob/main/questions.md#introductions and update your PR to include this information as well.

**Comment by somaiyappan** [comment]
I just updated it.

**Comment by ashish-mw** [comment]
Thank you @somaiyappan

**Pull request closed without merging**
