### PR TITLE
Asignment 

### PR DESCRIPTION
**Pull request by ktDeepak**
Task given is completed please verify and tell me

### CODE REVIEW

**Comment by ashish-mw** [comment]
Thanks for the PR @ktDeepak 

Please fill in the following too

```
- Who are you? What do you like building?
- Do you own a PC and have a good internet connection? Let's hear those specs 💪!
- Your stackoverflow, linkedin, personal site. Anything you'd want us to see.
- What programming languages have you messed around with?
- What sort of tooling is on your machine?
- Programming languages, compilers, runtimes etc
- What OS do you run?
- What editor/IDE do you use?
- Are you more into front-end or back-end? (If you're into web development).
- Are you interested in AI/ML, Systems Programming or anything outside your current domain.
- What are you learning now?
```

**Comment by ktDeepak** [comment]
1) My name is Deepak, i am  MERN fullstack developer.
      I would  like to build  WEB Applications, Ecomerce Applications and
Single Page Applications
2) Yes i have own PC , Dell
3)   linkedin-  deepak-k-taraganahalli -50113124b
      github-  github.com/ktDeepak
       mailid- ***@***.***
4) The programing language i meshed with is javascript and sql
5)  VS Code, Git , Nodejs,Postman ,Mongodb,Xamp
6) Javascript and Nodejs
7) Windows 10
8) VS code
9) Front end 60% and Back end 40%
10) Yes i am interested in AI
11) My learnings are new Advance Reactjs and Devops

**Comment by ashish-mw** [comment]
Thanks, @ktDeepak 
We'll get back to you.

**Comment by ktDeepak** [comment]
Any update?

**Comment by ktDeepak** [comment]
Any updates? Regarding Assignment submission

**Pull request closed without merging**
